### ISSUE TITLE
InsertComment

### ISSUE THREAD

**Issue by xich** [mpickering/apply-refact#9]
Does the `InsertComment` refactoring work? It requires a `SrcSpan` and I'm trying to figure out how to calculate that. Should it be a zero length span at the right line and column?

When I tried to use it, I got an error from `findGen`, which looks like it is trying to find an expression for replacement. Or do I just need to find an expression to attach the comment to? (It vaguely looks like this is what is going on, but I don't yet understand annotations.)

**Comment by mpickering** [comment]
To answer your question directly, you need to provide the `SrcSpan` of the expression to attach the comment to. For two reasons,

1. The only way to insert comments is by attaching them to something. (and placing them in the annotations map)
2. The `SrcSpan` might not be the actual location of the expression, it is used as a key so we can continue to refer to the same expression as it moves around.

So saying that, it doesn't make sense to provide an operation which allows you to insert a comment at a specific location because at the transformation stage all that information is lost.

I will answer more about comments on the other issue you opened.
